baseURL: 'https://lijemutu.github.io/unapuertasecreta.github.io/'
languageCode: 'en-us'
title: 'Una puerta secreta - blog'
theme: 'PaperMod'
params:
    homeInfoParams:
        Title: Date una vuelta por este lugar
        Content: Un blog dónde se habla un poco de todo, este trabajo es una muestra de lo que la programación puede hacer

    socialIcons: # optional
        - name: "github"
          url: "https://github.com/lijemutu"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/elopezrfis/"
    ShowShareButtons: true
    ShowReadingTime: true
    ShowBreadCrumbs: true
    ShowPostNavLinks: true
    env: production
menu:
    main:
        - identifier: Personal
          name: Personal
          url: /posts/
          weight: 10
        - identifier: Público
          name: Público
          url: /public/
          weight: 20



