baseURL: 'https://unapuertasecreta.me/'
languageCode: 'es-us'
title: 'Una puerta secreta - blog'
theme: 'PaperMod'
googleAnalytics: G-9CT9CGJ7GW
defaultContentLanguage: es
enableRobotsTXT: true
languages:
  es:
    title: 'Una puerta secreta - blog'
    weight: 1
  en:
    title: 'A secret door - blog'
    weight: 2
params:
    title: Una puerta secreta - blog
    description: "Este es un blog personal donde escribo acerca de mis proyectos personales que más me apasionan. Ciencia, programación y tecnología lo puedes encontrar aquí."
    keywords: [Desarrollo de software,Software development, Python, 'C#',aws,railway,physics,física,apps,bootcamp,sueldo,negocio,programación,programming,coding,code,development,dotnet,git,github,atlassian,azure,gcp,portfolio,blog,personal,mexico,spanish,espanol ]
    author: Erick López Reynoso
    homeInfoParams:
        Title: Date una vuelta por este lugar
        Content: Un blog dónde se habla un poco de todo, este trabajo es una muestra de lo que la programación puede hacer

    socialIcons: # optional
        - name: "github"
          url: "https://github.com/lijemutu"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/elopezrfis/"
    ShowShareButtons: true
    ShowReadingTime: true
    ShowBreadCrumbs: true
    ShowPostNavLinks: true
    env: production
menu:
    main:
        - identifier: Personal
          name: Personal
          url: /posts/
          weight: 10
        - identifier: Público
          name: Público
          url: /public/
          weight: 20



